# The URL the site will be built for
base_url = "https://wendajiang.github.io"
title = "「靡不有初，鲜克有终」"
description = "blog of david"

# The default language; used in feeds and search index
# Note: the search index doesn't support Chinese/Japanese/Korean Languages
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# whether to generate a feed file for the site
generate_feed = true

# when set to "true", the generated html files are minified
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

taxonomies = [
    {name = "tags"},
]


ignored_content = ["*.png", "*/README.md", "*/part3.md", "*/gsl-intro.md", "*/CONTRIBUTING.md"]

hard_link_static = true

[search]
# Whether to include the title of the page/section in the index
include_title = true
# Whether to include the description of the page/section in the index
include_description = false
# Whether to include the rendered content of the page/section in the index
include_content = true


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "dracula"
render_emoji = true

extra_syntaxes_and_themes = ["syntaxes"]

[extra]
# Put all your custom variables here
author = "David"
github = "https://github.com/wendajiang"
email = "wendajiang1993@gmail.com"
ganalytics = ""  # Google Analytics code

# Set HTML file language
language_code = "en-US"

# Set theme-color meta tag for Chrome browser
theme_color = "#fff"

# More about site's title
title_separator = "|"  # set as |, -, _, etc
title_addition = "David Blog"

# Set date format in blog publish metadata
timeformat = "%Y-%m-%d %H:%M:%S" # e.g. 2021-05-01 09:19:42
timezone = "UTC"

## Math settings
# options: true, false. Enable math support globally,
# default: false. You can always enable math on a per page.
math = true
library = "katex"  # options: "katex", "mathjax". default is "katex".

[extra.open]
enable = true
image = "david.png"
og_locale = "en_US"

[extra.show]
tags = true
links = true

[extra.gitalk]
ClientId = 'a17500877ddbb2dd70b9'
ClientSecret = '77e1c5816e97e2473c0a617bd0e3ece99f33559f'
Owner = 'wendajiang'
Repo = 'wendajiang.github.io'

## JSON-LD
[extra.schema]
type = "Organization"
logo = "david.png"
github = "https://github.com/wendajiang"
section = "blog" # see config.extra.main~url
## Sitelinks Search Box
site_links_search_box = true

[[extra.menu.social]]
name = "GitHub"
pre = '<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"></path></svg>'
url = "https://github.com/wendajiang"
post = "v0.1.0"
weight = 20


[[extra.menu.main]]
name = "Books"
section = "books"
url = "/books/effective-modern-cpp"
weight = 10