name: Build and deploy

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: checkout main
        uses: actions/checkout@v3.3.0
      - name: build and deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
